language: bash

services:
  - docker

addons:
  ssh_known_hosts: 164.90.168.125
  
env:
  global:
    secure: mL6Z6Cb/lO0stkZ86aExdOYytXZeru347lpD1fbPjIszAC1Rs7JOrGgm8X4bCzWF1AmjKiCHzApGZOAZYjUqzFiA61lvO9zH1dfrGjzqIYMoqnBIiZ46fYoVGx4iNKosdmOT/24zagIpxec3oor/EeBhf1vJQhOACwCg2U1EQLVLcAUhhghRo0dwIN+JOrKtchtWvSB4H+mJ1zFwkIEfktR0tp+u3OmmyKjMMNBu37ZVNSJrkNssPY0XmyBgNQGYsyZ2wgwKhSoQd3Dwp9JGbwLXwmbZ+hBKcMmG0rAmfiupijIRlfwNWb/g3ujKsIW0+o4yYcDW+CtraFZbfWJMJk5Hvig5EgVd9Jm/ozBDEU3MSVSCBEGHESB1pYgAove5UokIAuesgbAqd7pQ19B6kHVRkeR5kQ22JsfsOZ9xvxdPUmoERRsn9Kk9OkonyPflQsbUFVqNZHXmAe7WbxpyaYhTjI+erBs3LRg+EjhQAHAVBpYrloA201Bt3BRAXW17QOUo4oI4NWfurHNTSFNrP90PDXLzO6thYjCfjABlUVZ9kmKDBLrBmT0yEw/0IwF2kZqRs6frHigYuiBuo1EgRcZVAeJ3mHdtcGkNrPhy5ZahCoQbUJ2J3rUnf3jOPhF11gK8jYscRx7AtouY6a/5dPggFvFC7K1JFqDSmfCtyRg=

before_install:
  - docker build -t kimlehtinen/website:v0.0.1-build-$TRAVIS_JOB_NUMBER ./app
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
before_deploy:
  - echo $DEPLOY_RSA_PSW | gpg --yes --passphrase-fd 0 deploy_rsa.gpg
  - mv deploy_rsa /tmp
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host 164.90.168.125\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ls -la $TRAVIS_BUILD_DIR
deploy:
  - provider: script
    script: bash docker_push.sh
    on:
      branch: master
  - provider: script
    script: bash update_remote_version.sh
    on:
      branch: master

#after_deploy:
  #- sudo sh ./run_proxy.sh
  #- sudo sh ./deployment.sh
