language: bash

services:
  - docker

addons:
  ssh_known_hosts: 164.90.168.125
  
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker build -t kimlehtinen/website:v0.0.1-build-$TRAVIS_JOB_NUMBER ./app
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    script: bash docker_push.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR deploy@164.90.168.125:/home/deploy/website
    on:
      branch: master

after_deploy:
  - sudo sh ./run_proxy.sh
  - sudo sh ./deployment.sh
