version: '3'

services:
  app:
    image: kimlehtinen/website:latest
    labels:
      - "traefik.enable=true"
      - "traefik.backend=flask_app"
      - "traefik.backend.healthcheck.path=/health"
      - "traefik.backend.healthcheck.interval=1s"
      - "traefik.frontend.rule=Host:kimlehtinen.com"
      - "traefik.basic.port=5000"
      - "traefik.basic.protocol=http"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=5443"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_webgateway
