version: '3'

services:
  traefik:
    image: traefik:v1.7.16 # The official Traefik docker image
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080" # traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # traefik listents to events in docker
      - ./traefik.toml:/traefik.toml

networks:
  webgateway:
    driver: bridge
